# Generated by Django 5.0 on 2023-12-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
